import type { LucideIcon } from "lucide-react";
import {
  Aperture,
  Box,
  Brush,
  Calendar,
  Camera,
  CircleUser,
  Clapperboard,
  Crop,
  FileText,
  Film,
  FolderOpen,
  Frame,
  GalleryHorizontal,
  Grid2x2,
  Hash,
  Image,
  Images,
  Layers,
  LayoutGrid,
  Link2,
  Megaphone,
  MessageSquare,
  Mic,
  Newspaper,
  Package,
  Paintbrush,
  Palette,
  Pencil,
  PenLine,
  Play,
  Radio,
  Scan,
  ShoppingBag,
  Smile,
  Sparkles,
  Sticker,
  Store,
  Type,
  UserRound,
  Users,
  Video,
  Volume2,
  Wand2,
  Workflow,
} from "lucide-react";

export const GENERATION_NAV_LUCIDE_ICONS: { name: string; Icon: LucideIcon }[] = [
  { name: "Sparkles", Icon: Sparkles },
  { name: "LayoutGrid", Icon: LayoutGrid },
  { name: "Image", Icon: Image },
  { name: "Images", Icon: Images },
  { name: "Film", Icon: Film },
  { name: "Video", Icon: Video },
  { name: "Paintbrush", Icon: Paintbrush },
  { name: "Pencil", Icon: Pencil },
  { name: "PenLine", Icon: PenLine },
  { name: "Brush", Icon: Brush },
  { name: "Palette", Icon: Palette },
  { name: "Package", Icon: Package },
  { name: "Box", Icon: Box },
  { name: "UserRound", Icon: UserRound },
  { name: "Users", Icon: Users },
  { name: "CircleUser", Icon: CircleUser },
  { name: "Type", Icon: Type },
  { name: "FileText", Icon: FileText },
  { name: "Newspaper", Icon: Newspaper },
  { name: "MessageSquare", Icon: MessageSquare },
  { name: "Mic", Icon: Mic },
  { name: "Volume2", Icon: Volume2 },
  { name: "Layers", Icon: Layers },
  { name: "Frame", Icon: Frame },
  { name: "Grid2x2", Icon: Grid2x2 },
  { name: "GalleryHorizontal", Icon: GalleryHorizontal },
  { name: "Camera", Icon: Camera },
  { name: "Aperture", Icon: Aperture },
  { name: "Clapperboard", Icon: Clapperboard },
  { name: "Play", Icon: Play },
  { name: "Wand2", Icon: Wand2 },
  { name: "Megaphone", Icon: Megaphone },
  { name: "ShoppingBag", Icon: ShoppingBag },
  { name: "Store", Icon: Store },
  { name: "Scan", Icon: Scan },
  { name: "Crop", Icon: Crop },
  { name: "Smile", Icon: Smile },
  { name: "Sticker", Icon: Sticker },
  { name: "Hash", Icon: Hash },
  { name: "Link2", Icon: Link2 },
  { name: "Calendar", Icon: Calendar },
  { name: "Radio", Icon: Radio },
  { name: "FolderOpen", Icon: FolderOpen },
  { name: "Workflow", Icon: Workflow },
];

const lucideByName = new Map(GENERATION_NAV_LUCIDE_ICONS.map((item) => [item.name, item.Icon]));

export function generationNavLucideIcon(name: string): LucideIcon {
  return lucideByName.get(name) ?? Sparkles;
}
